name: CD pipeline
on: push
jobs:
  downloading-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with: 
          name: war.zip
          path: src/War.zip
          repository: likhithayeturi06/angular11-spring-boot2-mysql
          token: ${{secrets.AUTHORIZATION}}
          